[secrets]
db_key= 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZHF4d2tpd3R3Y2xkeGF5enVkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNTcwNzgwMywiZXhwIjoyMDMxMjgzODAzfQ.up4rECDxt98YSwie-9nKy2sFhfYwcjF4fjeTxMdgtYE'
url='https://tbdqxwkiwtwcldxayzud.supabase.co'
admin_password= 'abc'