[secrets]
db_key= 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZHF4d2tpd3R3Y2xkeGF5enVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU3MDc4MDMsImV4cCI6MjAzMTI4MzgwM30.AC_nObgL4PbSbnuOP67xnCyj3LGE315YFsE70nIW4uE'
url='https://tbdqxwkiwtwcldxayzud.supabase.co'
admin_password= 'abc'